### ISSUE TITLE
Avoid raising RuntimeError when Notifications API isn't configured

### ISSUE THREAD

**Issue by alextreme** [maykinmedia/notifications-api-common#10]
Encountered in the Objects API, Open Inwoner and in Open Klant, with notifications-api-common we currently raise a RuntimeError if the Notifications API client is unconfigured, causing a 500 when creating an instance. This causes irritation as users explicitly have to know about and disable notifications with the NOTIFICATIONS_DISABLED setting (which is properly documented but isn't mentioned in the exception).

Now I get why the Notifications API could be seen as mandatory for Open Zaak to adhere to the VNG ZGW API and that the notifications-api-common library was based on vng-api-common which was primarily developed for the reference implementations for the ZGW APIs. However as we're using notifications-api-common more broader for the Objects API, Open Inwoner and Open Klant, applications where notifications are optional.

As such I propose simply logging the fact that the notifications aren't configured and proceeding instead of raising a RuntimeError.

**Comment by alextreme** [comment]
Quickly discussed with Joeri last week but I'm unsure what both your stances are in this, if there is disagreement on if this is a useful change lets discuss this at the office

**Comment by alextreme** [comment]
Thinking about this more we could also have a setting NOTIFICATIONS_OPTIONAL to allow each application to choose between mandatory or optional notifications. If this is preferable I'll update my PR accordingly.

**Comment by sergei-maertens** [comment]
I don't really understand why you would use this package if notifications are not relevant? Unless you want to lose the guarantee that CRUD actions in the API produce notifications that other services can tap into, which I'm afraid creates a whole different class of problems due to inconsistent behavior depending on whether the notifs API is configured or not

**Comment by alextreme** [comment]
We have multiple installs for the mentioned components, but only in certain cases are generating notifications necessary. Open Klant for instance is used with notifications within Den Haag (and for that it's important) but for Open Klant within KISS notifications aren't necessary.

But that notifications are necessary for syncing does make this risky. I'll think about this some more.

**Comment by sergei-maertens** [comment]
I'm not opposed to the idea of a setting (not configurable via envvars) like `NOTIFICATIONS_BREAK_HARD_DEPENDENCY` so that each component can specify whether it's a soft or hard dependency. I do think the name of the setting should reflect the possible impact and scare people when disabling it. Then the `RuntimeError` could become a `logger.warning` call instead + bail out of that code path.

**Comment by alextreme** [comment]
Discussed:
- `NOTIFICATIONS_GUARANTEE_DELIVERY`, default=True. If False don't raise
- logger.warning instead of logger.info
- "Not notifying, Notifications API configuration is broken or absent."

**Comment by alextreme** [comment]
Issue has been discussed and resolved via #11 , closing the issue.
